export const dareChallenges = [
  'Appelle un numéro au hasard',
  'Montre-moi une photo de toi où tu te trouves belle/beau',
  'Lis à voix haute ton dernier message envoyé',
  "Envoie un message à un de tes parents et dis 'Je t'aime'",
  'Montre tes 2 dernières vidéos TikTok favorites',
  'On lance chacune une pièce. À chaque fois que ça tombe sur pile, une personne enlève un vêtement. Le premier sans vêtement a le droit à une minute de caresses',
  'Colle-moi contre le mur et chuchote-moi tes désirs',
  'Fais 20 pompes',
  'Montre-moi l’historique de tes recherches Google',
  'Fais-moi un compliment sincère',
  'Chante ta chanson préférée pendant une minute',
  'Fais semblant de me demander en mariage de manière improbable',
  "Imite un personnage de film. Je dois deviner qui c'est",
  'Fais-moi deviner une chanson en la fredonnant',
  'Fais-moi un portrait de moi en une minute',
  'Partage une anecdote amusante de ton enfance',
  'Raconte une blague qui te fait toujours rire.',
  'Écris une note dans mon téléphone que je pourrai lire demain',
  'Cache un objet dans la pièce pendant que je ferme les yeux. Je dois le retrouver',
  'Fais-moi un compliment inattendu',
  'Prends une photo de nous dans une pose drôle',
  'Raconte-moi un secret que tu as gardé depuis longtemps',
  'Choisis une chanson et fais du karaoké',
  'Fais-moi une promesse que tu tiendras cette semaine',
  "Chuchote-moi à l'oreille un fantasme secret",
  'Fais-moi un massage sensuel de 5 minutes',
  'Déshabille-moi avec tes yeux pendant 30 secondes',
  'Embrasse-moi passionnément pendant une minute',
  'Rapproche-toi doucement de mes lèvres sans les toucher',
  'Regarde-moi dans les yeux et dis-moi ce que tu aimerais faire',
  'Enlève un vêtement de ton choix',
  'Laisse-moi deviner ce que tu veux faire sans parler',
  'Écris un gage sur un bout de papier et donne-le-moi',
  'Fais-moi un bisou sur la partie de mon corps que tu préfères',
  'Touche doucement mes hanches avec tes deux mains',
  "Toi et moi, nous sommes des acteurs d'une vidéo X, raconte ce qu'il s’est passé",
];
