export const truthQuestions = [
  "Qu'as-tu dit de moi à tes amis la première fois ?",
  'Quel est ton souvenir le plus gênant ?',
  "Qu'est-ce qui a changé en toi depuis notre rencontre ?",
  'Quelle est la chose la plus folle que tu aimerais faire avec moi ?',
  'Si tu devais me décrire en 3 mots, lesquels choisirais-tu ?',
  "Qu'aimerais-tu que je te demande plus souvent ?",
  "Que pensais-tu de moi la première fois que tu m'as vu ? Et comment me vois-tu maintenant ?",
  "Quelles sont les 3 choses pour lesquelles tu m'aimes et m'apprécies aujourd'hui ?",
  "Y a-t-il quelque chose que nous, ou l'un de nous, pourrions améliorer ?",
  'Si demain je perdais la mémoire, quelle serait la première chose que tu me dirais sur nous ?',
  "Qu'est-ce qui, à ton avis, m'a fait tomber amoureux(se) de toi ?",
  "C'est quoi pour toi de vivre une Vie Extraordinaire ?",
  'Quelle est ta plus grosse peur concernant le futur ?',
  "Qu'est-ce qui, selon toi, détruit une relation, en dehors de la tromperie et du mensonge ?",
  'Quelle est mon habitude la plus bizarre que tu adores ?',
  "T'arrive-t-il de comparer notre relation à celle d'autres personnes ? Si oui, lesquelles et pourquoi ?",
  "Quelle est la partie de notre relation qui, selon toi, a le plus besoin d'être travaillée ?",
  'Sur une échelle de 1 à 10, comment estimes-tu la manière dont je te traite ?',
  "Qu'est-ce que tes parents t'ont fait subir que toi tu ne ferais pas subir à tes enfants ?",
  'Sur une échelle de 1 à 10, où dirais-tu que notre relation se situe en ce moment ?',
  'Est-ce que tu me mentirais pour ne pas me rendre triste ?',
  'Quelle petite chose de notre quotidien symbolise le mieux notre couple ?',
  "C'est quoi ton meilleur souvenir avec moi ?",
  "Y a-t-il un moment où tu t'es senti(e) incompris(e) dans notre couple ?",
  "Qu'est-ce que je fais qui te donne le sentiment d'être aimé(e) ?",
  "De quoi as-tu besoin de ma part que tu ne reçois pas à l'heure actuelle ?",
  "Est-ce que tu arriverais à t'excuser même si tu penses que ce n'est pas de ta faute ?",
  "C'est quoi la dernière fois que je t'ai fait mal au cœur ?",
  'Quel est le trait de mon caractère que je dois améliorer ?',
  'Quelle est la plus longue période que tu as passée sans te doucher ?',
  'Quel est le cadeau que tu voudrais recevoir pour ton prochain anniversaire ?',
  'Quelle marque de voiture veux-tu acheter ?',
  'Quelles sont les pratiques sexuelles qui te dégoûtent ?',
  "Qu'est-ce qui te procure des frissons ?",
  "Aimerais-tu être filmé(e) pendant l'acte d'amour ?",
  'Quelle est ta position préférée ?',
  'Si on ne pouvait pas devenir parents naturellement, souhaiterais-tu adopter ?',
  'Quel est ton artiste musical préféré ?',
  "Est-ce que tu aimes qu'on te tire les cheveux ?",
  'Est-ce que tu peux jouir avec un cunnilingus ?',
  "Avec combien de femmes ou d'hommes serais-tu prêt(e) à faire l'amour en même temps ?",
  "Aimerais-tu faire l'amour avec moi sur ton lieu de travail ?",
  'As-tu déjà fait un rêve érotique ? Si oui, raconte.',
  "Où rêverais-tu de faire l'amour ?",
];
